version: '3.3'

services:
  mariadb:
    build: ./mariadb
    restart: always
    container_name: mariadb-container
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"
      - MARIADB_ROOT_PASSWORD="test1234"
    ports:
      - '3333:3306'
    # expose 는 컨테이너끼리 노출할 포트!
    # expose:
    #   - '3333'

  redis:
    build: ./redis
    restart: always
    container_name: redis-container
    ports:
      - '6666:6379'
    # expose 는 컨테이너끼리 노출할 포트!
    # expose:
    #   - '6666'